config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/about', to: 'welcome#show'

  resources :users, except: [:new, :show, :index]
  get '/signup', to: 'users#new'
  get '/users/:id', to: 'users#show', as: 'profile'

  resources :sessions, only: [:create]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  resources :npos do 
    resources :tasks
    resources :projects, only: [:index]
  end
  get '/npoform', to: 'npos#new'

  # resources :tasks use this later for task functionality

  resources :projects, only: [:create, :show, :edit, :update]
end


#        Prefix Verb   URI Pattern                            Controller#Action
#          root GET    /                                      welcome#index
#         users POST   /users(.:format)                       users#create
#     edit_user GET    /users/:id/edit(.:format)              users#edit
#          user PATCH  /users/:id(.:format)                   users#update
#               PUT    /users/:id(.:format)                   users#update
#        signup GET    /signup(.:format)                      users#new
#       profile GET    /users/:id(.:format)                   users#show
#      sessions POST   /sessions(.:format)                    sessions#create
#         login GET    /login(.:format)                       sessions#new
#        logout GET    /logout(.:format)                      sessions#destroy
#     npo_tasks GET    /npos/:npo_id/tasks(.:format)          tasks#index
#               POST   /npos/:npo_id/tasks(.:format)          tasks#create
#  new_npo_task GET    /npos/:npo_id/tasks/new(.:format)      tasks#new
# edit_npo_task GET    /npos/:npo_id/tasks/:id/edit(.:format) tasks#edit
#      npo_task GET    /npos/:npo_id/tasks/:id(.:format)      tasks#show
#               PATCH  /npos/:npo_id/tasks/:id(.:format)      tasks#update
#               PUT    /npos/:npo_id/tasks/:id(.:format)      tasks#update
#               DELETE /npos/:npo_id/tasks/:id(.:format)      tasks#destroy
#  npo_projects GET    /npos/:npo_id/projects(.:format)       projects#index
#          npos GET    /npos(.:format)                        npos#index
#               POST   /npos(.:format)                        npos#create
#       new_npo GET    /npos/new(.:format)                    npos#new
#      edit_npo GET    /npos/:id/edit(.:format)               npos#edit
#           npo GET    /npos/:id(.:format)                    npos#show
#               PATCH  /npos/:id(.:format)                    npos#update
#               PUT    /npos/:id(.:format)                    npos#update
#               DELETE /npos/:id(.:format)                    npos#destroy
#       npoform GET    /npoform(.:format)                     npos#new
#      projects POST   /projects(.:format)                    projects#create
#  edit_project GET    /projects/:id/edit(.:format)           projects#edit
#       project GET    /projects/:id(.:format)                projects#show
#               PATCH  /projects/:id(.:format)                projects#update
#               PUT    /projects/:id(.:format)                projects#update

              

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :npo
  has_many :projects
  has_many :users, through: :projects
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def index
		@task = Task.all
		render :index
	end 

	def new
		@npo = Npo.find(params[:npo_id])
		@task = Task.new
		render :new
	end

	def create
		@npo = Npo.find(params[:npo_id])
		task = @npo.tasks.create(task_params)
		task.save
		redirect_to npo_path(@npo)		
	end

	def show 
		@task = Task.find(params[:id])
		render :show
	end

	def edit
		@task = Task.find(params[:id])
		if current_user.npos.tasks.include? @task
			render :edit
		else
			redirect_to login_path
		end
	end

	def update
	  task = Task.find(params[:id])
	  if user.is_npo.tasks.include? task
	    task.update_attributes(task_params)
	    redirect_to task_path(task)
	  else
	    redirect_to task_path
	  end
	end

	def destroy
	end

	private
	
	def task_params
		params.require(:task).permit(:issue, :description, :language, :framework)
	end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<div class="new-task">
  <div class="col-sm-4 col-sm-offset-4">
  <br>
      <div class="signupbox">
        <legend>Amazing Tasks</legend>
        <%= form_for @task do |f| %>
        <%= f.select :issue, options_for_select(
                        [
                            ["New Site", "New Site"],
                            ["Fix Something", "Fix Something"],
                            ["Add Feature", "Add Feature"],

                        ]
                    ), {}, class: "form-control col-sm-4" %>
      <br> 
      <br>
      <br>
           <%= f.text_area :description, class:"form-control", required: true, placeholder: "Description" %><br />
           <%= f.text_field :language, class:"form-control", required: true, placeholder: "Language" %><br />
           <%= f.text_field :framework, class:"form-control", required: true, placeholder: "Framework" %><br />
           <br>
           <%= f.submit "Submit", class:"btn btn-primary" %>
        <% end %>  
    </div> 
  </div>
</div>

app/views/tasks/index.html.erb
<h1>Hello World </h1> 



<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<br><br>
				<%= link_to "New Task", new_task_path(@task), class: "btn btn-success" %>
				<br><br>

				<% if current_user.npos.tasks.any? %>

					<!-- test -->
					<% if false %>

					<% @city.posts.reverse_each do |post| %>
						<div class="panel panel-warning">
							<div class="panel-heading">
								<%= image_tag post.user.avatar.url(:thumb), class: "thumbnail" %>
								<h3 class="panel-title username"> &nbsp<%= post.user.username %></h3>
							</div>
							<div class="panel-body">
								<p>Title: <%= post.title %> <br>Body: <%= post.body %> <br>
							  <% tag_cloud post.tag_counts, %w{s m l} do |tag, css_class| %>
    							<%= link_to tag.name, tag_path(tag.id), class: css_class %>
  							<% end %></p>
							<%= commontator_thread(post) %>
							</div>
							<% if post.user.id == session[:user_id] %>
								<div class="panel-footer">
									<%= link_to "Edit Post", edit_post_path(post), class: "btn btn-primary" %>
									<%= link_to "Delete Post",  post, method: :delete, class: "btn btn-danger"  %>
								</div>
							<% end %>
						</div>	
					<% end %>

					<!-- test -->
					<% end %>


				<% else %>
					<p>Please add a post<p>
				</div>
			</div>
		</div>
<% end %>

app/views/tasks/new.html.erb
<div class="new-task">
  <div class="col-sm-4 col-sm-offset-4">
  <br>
      <div class="signupbox">
        <legend>Submit A Task To Be Worked On</legend>
        <%= form_for [@npo, @task] do |f| %>
        <%= f.select :issue, options_for_select(
                        [
                            ["New Site", "New Site"],
                            ["Fix Something", "Fix Something"],
                            ["Add Feature", "Add Feature"],

                        ]
                    ), {}, class: "form-control col-sm-4" %>
      <br> 
      <br>
      <br>
           <%= f.text_area :description, class:"form-control", required: true, placeholder: "Description" %><br />
           <%= f.text_field :language, class:"form-control", required: true, placeholder: "Language" %><br />
           <%= f.text_field :framework, class:"form-control", required: true, placeholder: "Framework" %><br />
           <br>
           <%= f.submit "Submit", class:"btn btn-primary" %>
        <% end %>  
    </div> 
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="row">


  <center>
  <h3> Description of Task: </h3>
    <hr>
    Issue: <%= @task.issue %> <br> <br>
  
    Description: <%= @task.description %> <br> <br>

    Language: <%= @task.language %> <br> <br>

    Framework: <%= @task.framework %> <br> <br>
    </center>


  </div>
</div>