config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/about', to: 'welcome#show'

  resources :users, except: [:new, :show, :index]
  get '/signup', to: 'users#new'
  get '/users/:id', to: 'users#show', as: 'profile'

  resources :sessions, only: [:create]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  resources :npos do 
    resources :tasks
    resources :projects, only: [:index]
  end
  get '/npoform', to: 'npos#new'

  # resources :tasks use this later for task functionality

  resources :projects, only: [:create, :show, :edit, :update]
end


#        Prefix Verb   URI Pattern                            Controller#Action
#          root GET    /                                      welcome#index
#         users POST   /users(.:format)                       users#create
#     edit_user GET    /users/:id/edit(.:format)              users#edit
#          user PATCH  /users/:id(.:format)                   users#update
#               PUT    /users/:id(.:format)                   users#update
#        signup GET    /signup(.:format)                      users#new
#       profile GET    /users/:id(.:format)                   users#show
#      sessions POST   /sessions(.:format)                    sessions#create
#         login GET    /login(.:format)                       sessions#new
#        logout GET    /logout(.:format)                      sessions#destroy
#     npo_tasks GET    /npos/:npo_id/tasks(.:format)          tasks#index
#               POST   /npos/:npo_id/tasks(.:format)          tasks#create
#  new_npo_task GET    /npos/:npo_id/tasks/new(.:format)      tasks#new
# edit_npo_task GET    /npos/:npo_id/tasks/:id/edit(.:format) tasks#edit
#      npo_task GET    /npos/:npo_id/tasks/:id(.:format)      tasks#show
#               PATCH  /npos/:npo_id/tasks/:id(.:format)      tasks#update
#               PUT    /npos/:npo_id/tasks/:id(.:format)      tasks#update
#               DELETE /npos/:npo_id/tasks/:id(.:format)      tasks#destroy
#  npo_projects GET    /npos/:npo_id/projects(.:format)       projects#index
#          npos GET    /npos(.:format)                        npos#index
#               POST   /npos(.:format)                        npos#create
#       new_npo GET    /npos/new(.:format)                    npos#new
#      edit_npo GET    /npos/:id/edit(.:format)               npos#edit
#           npo GET    /npos/:id(.:format)                    npos#show
#               PATCH  /npos/:id(.:format)                    npos#update
#               PUT    /npos/:id(.:format)                    npos#update
#               DELETE /npos/:id(.:format)                    npos#destroy
#       npoform GET    /npoform(.:format)                     npos#new
#      projects POST   /projects(.:format)                    projects#create
#  edit_project GET    /projects/:id/edit(.:format)           projects#edit
#       project GET    /projects/:id(.:format)                projects#show
#               PATCH  /projects/:id(.:format)                projects#update
#               PUT    /projects/:id(.:format)                projects#update

              

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password


  validates_presence_of :password_confirmation

  # relationships
	has_many :npos
  has_many :projects
  has_many :tasks, through: :projects


# for profile photos
  has_attached_file :avatar,
                    :styles => { :medium => "150x150>", :thumb => "44x44>" },
                    :storage => :s3,
                    :s3_credentials => Proc.new { |a| a.instance.s3_credentials },
                    :path => "avatars/:id/:style/avatar.:extension",
                    :default_url => "https://s3.amazonaws.com/vagabondapps/avatars/Developerswithoutborders/avatar.png"
                        

                   		# :avatar, :presence => true,
 validates_attachment :avatar,
                      :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] },
                      :size => { :in => 0..100000.kilobytes }


  def s3_credentials
    { :bucket => ENV['S3_BUCKET'], :access_key_id => ENV['S3_PUBLIC_KEY'], :secret_access_key => ENV['S3_SECRET'] }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
     if current_user
       redirect_to profile_path(current_user)
     else
      @user = User.new
     render :new
      end
  end

  def create
    if current_user 
      redirect_to profile_path(current_user)
    else 
      user=User.new(user_params)
      if user.save 
        session[:user_id] = user.id
        if user.is_npo
          redirect_to npoform_path 

        else
        redirect_to profile_path(current_user)
        end
      else 
      redirect_to signup_path

      end
    end
  end

  def show
    @user = User.find(params[:id])
    render :show

  end

  def edit
    @user = User.find(current_user)
    render :edit
  end

  def update
    user = User.find(params[:id])
    if current_user
      # ill add these later (antonio)
      # flash[:notice] = "Successfully updated profile!"
      user.update_attributes(user_params)
      redirect_to profile_path(current_user)
    else
      flash[:error] = user.errors.full_messages.join(', ')
      redirect_to edit_profile_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    if current_user
      # flash[:error] = "Successfully deleted profile!"
      @user.destroy
      session[:user_id] = nil
      redirect_to root_path
    end
  end
  
  private 
    def user_params 
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :is_npo, :created_at, :avatar)
    end

    

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="col-sm-4 col-sm-offset-4">
  <br>
  <div class="signupbox">
    <%= form_for @user, :html => { :multipart => true } do |f| %>
      <%= f.label :username, "Username" %>:
      <%= f.text_field :username, class:"form-control", required: true %><br />
      <%= f.label :email, "Email" %>:
      <%= f.email_field :email, class:"form-control", required: true %><br />
      <%= f.label :password, "Password" %>:
      <%= f.password_field :password, class:"form-control", required: true %><br />
      <%= f.label :password, "Retype Password" %>:
      <%= f.password_field :password_confirmation, class:"form-control", required: true %><br />
      <%= f.radio_button(:is_npo, true) %>
      <%= f.label(:is_npo, "I Represent A Non-Profit Org.") %>&nbsp&nbsp <br>
      <%= f.radio_button(:is_npo, false) %>
      <%= f.label(:is_npo, "I'm A Developer") %>
      <br>
      <br>
      <%= f.file_field :avatar %>
      <br>
      <% if logged_in? %>
       <%= image_tag @user.avatar.url(:medium) %>
        Current Photo
        <br>
        <br>
        <br>
        <%= f.submit "Update Profile", class:"btn btn-primary" %>
        <%= link_to "Delete Account",  @user, method: :delete, class: "btn btn-danger"  %>
      <% else %>
        <%= f.submit "Join Us!", class:"btn btn-primary" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h3><center>Edit Your Profile </center></h3>
<%= render 'form' %>

app/views/users/new.html.erb
<h3><center> Signup </center></h3><%= render 'form' %>

app/views/users/show.html.erb
<!-- DEV INFO -->

<div class="container">
  <div class="row">

    <div class="col-md-4 thumbnail">
      <center>
      <%= image_tag @user.avatar.url(:medium) %>
	    <h3>Username: <%= @user.username %> </h3>
	    <p>Email: <%= @user.email %> </p>
	    <p>Date Joined: <%= @user.created_at %> </p>
      <% if @user.id == session[:user_id] %>
        <%= link_to "Edit Your Account", edit_user_path, class: "btn btn-primary" %>
      <% end %>
      </center>
    </div>  
    <div class="col-md-offset-5 thumbnail">
    <center>
    <% if logged_in? %>
      <% if current_user.is_npo == true %>
        <% if current_user.npos.any? %>
        <h3> Your NPO Organizations: </h3>
          <% @user.npos.each do |npo| %>
            <div class="well">
              <%= image_tag npo.avatar.url(:medium) %>
              <p><%= link_to npo.name, npo_path(npo) %></p>
            </div>    
          
        <% end %>
        <%= link_to "Add A Nonprofit Organization", new_npo_path, class: "btn btn-primary" %>
      <% end %>
    <% elsif current_user.is_npo ==false %>
     
			<h3> Projects Applied To: </h3>
      <hr>
      <% current_user.projects.each do |project| %> 
      <p>
      <%= link_to project.task.issue, npo_task_path(project.task.npo, project.task) %>  -
      <%= project.task.description %> </p>
       
        <% end %> 
      <% end %> 
      <% end %>
      <center>
  </div>
</div>


 


 

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>