config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/about', to: 'welcome#show'

  resources :users, except: [:new, :show, :index]
  get '/signup', to: 'users#new'
  get '/users/:id', to: 'users#show', as: 'profile'

  resources :sessions, only: [:create]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  resources :npos do 
    resources :tasks
    resources :projects, only: [:index]
  end
  get '/npoform', to: 'npos#new'

  # resources :tasks use this later for task functionality

  resources :projects, only: [:create, :show, :edit, :update]
end


#        Prefix Verb   URI Pattern                            Controller#Action
#          root GET    /                                      welcome#index
#         users POST   /users(.:format)                       users#create
#     edit_user GET    /users/:id/edit(.:format)              users#edit
#          user PATCH  /users/:id(.:format)                   users#update
#               PUT    /users/:id(.:format)                   users#update
#        signup GET    /signup(.:format)                      users#new
#       profile GET    /users/:id(.:format)                   users#show
#      sessions POST   /sessions(.:format)                    sessions#create
#         login GET    /login(.:format)                       sessions#new
#        logout GET    /logout(.:format)                      sessions#destroy
#     npo_tasks GET    /npos/:npo_id/tasks(.:format)          tasks#index
#               POST   /npos/:npo_id/tasks(.:format)          tasks#create
#  new_npo_task GET    /npos/:npo_id/tasks/new(.:format)      tasks#new
# edit_npo_task GET    /npos/:npo_id/tasks/:id/edit(.:format) tasks#edit
#      npo_task GET    /npos/:npo_id/tasks/:id(.:format)      tasks#show
#               PATCH  /npos/:npo_id/tasks/:id(.:format)      tasks#update
#               PUT    /npos/:npo_id/tasks/:id(.:format)      tasks#update
#               DELETE /npos/:npo_id/tasks/:id(.:format)      tasks#destroy
#  npo_projects GET    /npos/:npo_id/projects(.:format)       projects#index
#          npos GET    /npos(.:format)                        npos#index
#               POST   /npos(.:format)                        npos#create
#       new_npo GET    /npos/new(.:format)                    npos#new
#      edit_npo GET    /npos/:id/edit(.:format)               npos#edit
#           npo GET    /npos/:id(.:format)                    npos#show
#               PATCH  /npos/:id(.:format)                    npos#update
#               PUT    /npos/:id(.:format)                    npos#update
#               DELETE /npos/:id(.:format)                    npos#destroy
#       npoform GET    /npoform(.:format)                     npos#new
#      projects POST   /projects(.:format)                    projects#create
#  edit_project GET    /projects/:id/edit(.:format)           projects#edit
#       project GET    /projects/:id(.:format)                projects#show
#               PATCH  /projects/:id(.:format)                projects#update
#               PUT    /projects/:id(.:format)                projects#update

              

app/models/npo.rb
class Npo < ActiveRecord::Base
	has_many :tasks
	belongs_to :user
  has_many :projects, through: :tasks
 
# for Npo photos
  has_attached_file :avatar,
                    :styles => { :medium => "150x150>", :thumb => "44x44>" },
                    :storage => :s3,
                    :s3_credentials => Proc.new { |a| a.instance.s3_credentials },
                    :path => "avatars/:id/:style/avatar.:extension",
                    :default_url => "https://s3.amazonaws.com/vagabondapps/avatars/Developerswithoutborders/building.png"

                   		# :avatar, :presence => true,
 validates_attachment :avatar,
                      :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] },
                      :size => { :in => 0..100000.kilobytes }


  def s3_credentials
    { :bucket => ENV['S3_BUCKET'], :access_key_id => ENV['S3_PUBLIC_KEY'], :secret_access_key => ENV['S3_SECRET'] }
  end
  
end

app/controllers/npos_controller.rb
class NposController < ApplicationController
	def index 
		@npos = Npo.all
		render :show
	end

	def new
		@npo = Npo.new
		render :new
	end

	def create
		npo = current_user.npos.new(npo_params)
		if npo.save
			redirect_to npo_path(npo)
		else
			redirect_to root_path
		end
	end

	def show
		@npo = Npo.find(params[:id])
		render :show
	end

	def edit
		@npo = Npo.find(params[:id])
		render :edit
	end

  def update
    npo = Npo.find(params[:id])
    if current_user.npos.include? npo
        npo.update_attributes(npo_params)
        redirect_to npo_path(npo)
    else
      redirect_to signup_path
    end
  end

  def destroy
    npo = Npo.find(params[:id])
    if current_user.npos.include? npo
      npo.destroy
      redirect_to profile_path(current_user)
    else
      redirect_to login_path
    end
  end

	private 
	def npo_params 
		params.require(:npo).permit(:name, :about, :created_at, :avatar)
	end
end

app/helpers/npos_helper.rb
module NposHelper
end

app/views/npos/edit.html.erb
<div class="signuppage">
  <div class="col-sm-6 col-sm-offset-3">
  <br>
  <div class="signupbox">
    <legend>Edit Non-Profit Organization's Profile</legend>
    <%= form_for @npo do |f| %>
      <%= f.label :name, "Organization Name" %>:
      <%= f.text_field :name, class:"form-control", required: true %><br />
      <%= f.label :about, "Mission" %>:
      <%= f.text_area :about, class:"form-control", required: true %><br />
      <%= f.label :avatar, "Organization Logo (if available)" %>:
      <%= f.file_field :avatar %> 
        <%= image_tag @npo.avatar.url(:medium) %>
        <br>
        Current Photo
       <br>
       <br>
       <br>
      <%= f.submit "Update Your Profile", class:"btn btn-primary" %>
      <%= link_to "Delete This Organization", @npo, method: :delete, class:"btn btn-danger margin-right"  %>
    <% end %>
  </div>
  </div>
</div>

app/views/npos/index.html.erb
this is my index

app/views/npos/new.html.erb
<div class="signuppage">

  <div class="col-sm-6 col-sm-offset-3">
  <br>
    <div class="signupbox">
      <legend>Add Your Non Profit Organization</legend>
      <%= form_for @npo do |f| %>
        <%= f.label :name, "Organization Name" %>:
        <%= f.text_field :name, class:"form-control", required: true %><br />
        <%= f.label :about, "Mission" %>:
        <%= f.text_area :about, class:"form-control", required: true %><br />
        <%= f.label :avatar, "Organization Logo (if available)" %>:
        <%= f.file_field :avatar %>
        <br>
        <%= f.submit "Add Your NPO!", class:"btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/npos/show.html.erb
<div class="container">
  <div class="row">
   <div class="col-md-5">
		<div class="thumbnail"> <center>
			<%= image_tag @npo.avatar.url(:medium) %>
	    <h3><%= @npo.name %> </h3>
	    <h4>Our Mission: <%= @npo.about %> </h4>
	    <p>Date Joined: <%= @npo.created_at %> </p>
      <% if @npo.user.id == session[:user_id] %>
 			<%= link_to "Edit Your NPO Organization", edit_npo_path, class: "btn btn-primary" %>
      <% end %>
        <hr>
      <p>  <%= link_to @npo.projects.where(status: "Pending").count, npo_projects_path(@npo) %> Pending Requests </p> 
      </center>
		</div>
  </div>
  <div class="col-md-offset-5">
  	<div class="thumbnail"> 
    <center>		
			<% if @npo.tasks.any? %>
				<h3>Looking For Developer Help:</h3> <br>
	    	<% @npo.tasks.each do |task| %>
	    	<div class="well">
	  			<p>Issue:  <%= link_to task.issue, npo_task_path(@npo, task) %></p>
	  			<p>Description: <%= task.description %></p>
  				<% if logged_in? %>
  					<% if current_user.is_npo == false %>
  			 			<%= form_for :project, url: projects_path do |f| %>
								<%= f.hidden_field :task_id, class: "form-control", value: task.id%>
								<%= f.hidden_field :status, class: "form-control", value: "Pending"%>
								<%= f.submit "Interested!", class: "btn btn-primary" %>
           		<% end %>
        		<% end %>
        	<% end %>
	  		</div>
	  		<% end %>
	  		<% if @npo.user.id == session[:user_id] %>
	  			<%= link_to "Add A Task", new_npo_task_path(@npo), class: "btn btn-primary" %>
				<% end %>
			<% else %>
			<h3>No Tasks Currently Available</h3>
           <% if @npo.user.id == session[:user_id] %>
          <%= link_to "Add A Task", new_npo_task_path(@npo), class: "btn btn-primary" %>
        <% end %>
	  	<% end %>
      <center>  
		</div>
  </div>
</div>