config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/about', to: 'welcome#show'

  resources :users, except: [:new, :show, :index]
  get '/signup', to: 'users#new'
  get '/users/:id', to: 'users#show', as: 'profile'

  resources :sessions, only: [:create]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  resources :npos do 
    resources :tasks
    resources :projects, only: [:index]
  end
  get '/npoform', to: 'npos#new'

  # resources :tasks use this later for task functionality

  resources :projects, only: [:create, :show, :edit, :update]
end


#        Prefix Verb   URI Pattern                            Controller#Action
#          root GET    /                                      welcome#index
#         users POST   /users(.:format)                       users#create
#     edit_user GET    /users/:id/edit(.:format)              users#edit
#          user PATCH  /users/:id(.:format)                   users#update
#               PUT    /users/:id(.:format)                   users#update
#        signup GET    /signup(.:format)                      users#new
#       profile GET    /users/:id(.:format)                   users#show
#      sessions POST   /sessions(.:format)                    sessions#create
#         login GET    /login(.:format)                       sessions#new
#        logout GET    /logout(.:format)                      sessions#destroy
#     npo_tasks GET    /npos/:npo_id/tasks(.:format)          tasks#index
#               POST   /npos/:npo_id/tasks(.:format)          tasks#create
#  new_npo_task GET    /npos/:npo_id/tasks/new(.:format)      tasks#new
# edit_npo_task GET    /npos/:npo_id/tasks/:id/edit(.:format) tasks#edit
#      npo_task GET    /npos/:npo_id/tasks/:id(.:format)      tasks#show
#               PATCH  /npos/:npo_id/tasks/:id(.:format)      tasks#update
#               PUT    /npos/:npo_id/tasks/:id(.:format)      tasks#update
#               DELETE /npos/:npo_id/tasks/:id(.:format)      tasks#destroy
#  npo_projects GET    /npos/:npo_id/projects(.:format)       projects#index
#          npos GET    /npos(.:format)                        npos#index
#               POST   /npos(.:format)                        npos#create
#       new_npo GET    /npos/new(.:format)                    npos#new
#      edit_npo GET    /npos/:id/edit(.:format)               npos#edit
#           npo GET    /npos/:id(.:format)                    npos#show
#               PATCH  /npos/:id(.:format)                    npos#update
#               PUT    /npos/:id(.:format)                    npos#update
#               DELETE /npos/:id(.:format)                    npos#destroy
#       npoform GET    /npoform(.:format)                     npos#new
#      projects POST   /projects(.:format)                    projects#create
#  edit_project GET    /projects/:id/edit(.:format)           projects#edit
#       project GET    /projects/:id(.:format)                projects#show
#               PATCH  /projects/:id(.:format)                projects#update
#               PUT    /projects/:id(.:format)                projects#update

              

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Developers Without Borders</title>

	<link rel="shortcut icon" href="http://i51.photobucket.com/albums/f364/esbenbsmith/dwbicon_zps5gqyy0ms.png" type="image/x-icon" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/united/bootstrap.min.css">
	<link rel="stylesheet" href="animate.min.css">
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
</head>

<body>

	<nav class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="container-fluid">
	    	<div class="navbar-header">
	    		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	    			<span class="icon-bar"></span>
	    			<span class="icon-bar"></span>
	    			<span class="icon-bar"></span>
	    		</button>
	    		<a href="/" class="navbar-brand"> <%= image_tag "logosmall.png" %></a>
	    	</div>
			<div class="collapse navbar-collapse"> 
	    	<ul class="nav navbar-nav navbar-right">
	    		<!-- log in / log out -->
					<% if logged_in? %>

						<%= link_to "Logout", logout_path, class: "btn navbar-btn navbar-right btn-primary" %>
						<%= link_to "Profile", profile_path(current_user), class: "btn navbar-btn navbar-right btn-primary" %>
						<%= link_to "About", about_path, class: "btn navbar-btn navbar-right btn-primary" %>
			
					<% else %>
						<%= link_to "Login", login_path, class: "btn navbar-btn navbar-right btn-primary" %>
						<%= link_to "Sign Up", signup_path, class: "btn navbar-btn navbar-right btn-primary" %>
						<%= link_to "About", about_path, class: "btn navbar-btn navbar-right btn-primary" %>
					<% end %>
	    		</ul>
	    	</div>
		</div>
	</nav> 
	
	<%= yield %>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>